API_LANG_MAP = {
    "ru": "ru",
    "en": "en",
    "kk": "ru" 
}

def get_api_lang_code(lang="ru"):
    """Получает код языка для API OpenWeatherMap"""
    return API_LANG_MAP.get(lang, "ru")

TEXTS = {
    "ru": {
        "unknown_command": "😔 Я вас не понял. Используйте команды меню.",
        "decorative_message_menu": "Выберите опцию:",
        "decorative_message_settings": "Выберите настройку:",
        "basic_keyboard_button_1": "🌤 Узнать погоду",
        "basic_keyboard_button_2": "📅 Прогноз погоды",
        "basic_keyboard_button_3": "⚙️ Настройки",
        "settings_keyboard_button_1": "🏙 Изменить город",
        "settings_keyboard_button_2": "🔔 Уведомления",
        "settings_keyboard_button_3": "☀️ Погодные данные",
        "settings_keyboard_button_4": "📏 Единицы измерения",
        "settings_keyboard_button_5": "↩ Назад",
        "settings_keyboard_button_language": "🌍 Язык",
        "error_unknown_city": "⚠ Сначала укажите ваш город в настройках.",
        "error_unknown_forecast": "⚠ Не удалось получить прогноз погоды.",
        "error_issue_forecast": "⚠ Произошла ошибка при обработке прогноза.",
        "forecast_header": "<b>{day_name}, {date}</b>",
        "forecast_desc": "▸ Погода: {description}",
        "forecast_temp_range": "▸ Температура: от {min}{unit} до {max}{unit}",
        "forecast_temp_single": "▸ Температура: {temp}{unit}",
        "forecast_feels": "▸ Ощущается как: {temp}{unit}",
        "forecast_humidity": "▸ Влажность: {val}%",
        "forecast_precip": "▸ Вероятность осадков: {val}%",
        "forecast_pressure": "▸ Давление: {val} {unit}",
        "forecast_wind": "▸ Скорость ветра: {val} {unit}",
        "forecast_wind_dir": "▸ Направление ветра: {dir} ({deg}°)",
        "forecast_gust": "▸ Порывы ветра: {val} {unit}",
        "forecast_clouds": "▸ Облачность: {val}%",
        "forecast_visibility": "▸ Видимость: {val} м",
        "separator": "─" * 21,
        "greet_returning": "С возвращением, {name}!\nВаш основной город — {city}.",
        "greet_new": "Привет, {name}!\n\nЧтобы начать пользоваться ботом, отправьте свои координаты или напишите город вручную.",
        "button_geo": "📍 Отправить координаты",
        "error_no_city": "⚠ Для начала укажите свой город.",
        "error_weather_fetch": "⚠ Не удалось получить данные о погоде.",
        "weather_current_header": "Сейчас в г.{city}:",
        "weather_footer": "⛄️ Одевайтесь теплее!",
        "changecity_current": "▸ Ваш текущий город — {city}. \n\nВведите название нового города для обновления.",
        "changecity_none": "Вы ещё не указали свой город! \nУкажите новый город.",
        "btn_cancel": "✖ Отмена",
        "notifications_menu_btn": "🔔 Уведомления",
        "notifications_menu_text": "Выберите уведомления, которые вы хотите получать:",
        "error_user_not_found": "Ошибка: пользователь не найден.",
        "stop_success": "🔕 Бот больше не будет присылать уведомления.\nДля включения уведомлений зайдите в настройки.",
        "stop_error": "Произошла ошибка при отключении уведомлений. Попробуйте позже.",
        "daily_forecast_title": "<blockquote>📅 Ежедневный прогноз погоды</blockquote>",
        "daily_forecast_updated": "[Обновлено в {time}]",
        "settings_units_header": "Сейчас ваши единицы измерения выглядят так:",
        "settings_units_temp": "▸ Температура: {val}",
        "settings_units_pressure": "▸ Давление: {val}",
        "settings_units_wind": "▸ Скорость ветра: {val}",
        "settings_units_choose": "Выберите параметр для изменения:",
        "error_user_not_found_start": "Ошибка: пользователь не найден. Попробуйте /start.",
        "btn_back": "↩ Назад",
        "settings_weather_data_btn": "☀️ Погодные данные",
        "settings_weather_data_text": "Выберите данные, которые будет показывать бот:",
        "menu_weather_now": "🌤 Узнать погоду",
        "menu_forecast": "📅 Прогноз погоды",
        "menu_settings": "⚙️ Настройки",
        "menu_change_city": "🏙 Изменить город",
        "menu_notifications": "🔔 Уведомления",
        "menu_back": "↩ Назад",
        "menu_units": "📏 Единицы измерения",
        "menu_weather_data": "☀️ Погодные данные",
        "menu_language": "🌍 Язык",
        "help_title": "Основные команды бота:",
        "help_start": "▸ /start — Запустить бота.",
        "help_stop": "▸ /stop — Отключить бота.",
        "help_weather": "▸ /weather — Узнать текущую погоду.",
        "help_changecity": "▸ /changecity — Сменить город.",
        "help_forecast": "▸ /weatherforecast — Получить прогноз погоды.",
        "help_help": "▸ /help — Получить список доступных команд.",
        "changecity_prompt_retry": "Введите название нового города для обновления!",
        "changecity_error_command": "‼️ Отправьте название города, а не команду!",
        "changecity_error_invalid": "‼️ Название города может содержать только буквы, пробелы и дефисы!",
        "changecity_success_update": "Теперь ваш основной город — {city}!",
        "changecity_success_same": "г.{city} остался вашим основным городом.",
        "greet_success_end": "☀️ Приятного использования бота!",
        "error_invalid_city_command": "‼️ Отправьте название города, а не команду!",
        "error_invalid_city_chars": "‼️ Название города может содержать только буквы, пробелы и дефисы!",
        "error_city_not_found_coords": "Не удалось определить город по координатам. Введите его вручную.",
        "error_no_input": "Пожалуйста, введите город или отправьте координаты.",
        "settings_unit_select_prompt": "Выберите единицу измерения {param}:",
        "unknown_direction": "Неопределено",
        "error_technical_glitch": "Упс... Похоже, произошли небольшие технические шоколадки!\nОтправьте повторный запрос немного позже ~o~",
        "weather_summary_clear": "🌤 Сегодня осадков не ожидается.",
        "weather_summary_range": "{emoji} {desc} ожидается с {start} до {end}.",
        "weather_summary_single": "{emoji} {desc} ожидается в {time}.",
        "language_select_prompt": "Выберите язык интерфейса:",
        "language_set_success": "✅ Язык изменен на Русский.",
        "warning_no_forecast": "⚠ Нет прогноза на дату {date} для города {city}",
        "forecast_footer": "❄️ Холод всегда предшествует весне.",
        "forecast_menu_title": "Выберите время, для получепния прогноза погоды:",
        
        # --- ТЕКСТА ДЛЯ ТАЙМЕРА ---
        "notification_header": "<blockquote>{emoji} Внимание!</blockquote>\nПогода в г.{city} изменилась!",
        "notification_footer": "\n🌟 Не падай духом — погода ещё наладится.",
        "notification_trend_up": "⇑",
        "notification_trend_down": "⇓",
        "notification_trend_arrow": "▸",

        "help_header": "🤖 <b>Список доступных команд:</b>",
        "help_cmds": {
            "/start": "🏠 Главное меню",
            "/weather": "🌤 Погода сейчас",
            "/forecast": "📅 Прогноз",
            "/settings": "⚙️ Настройки",
            "/changecity": "🏙 Сменить город",
            "/help": "ℹ️ Справка"
        },
        "help_footer": "💡 <i>Напишите название города, чтобы узнать погоду в нём.</i>",

        "btn_forecast_today": "🌤 Сегодня",
        "btn_forecast_tomorrow": "🌧 Завтра",
        "btn_forecast_week": "📆 Неделя",
        "unit_temp_label": "Температура",
        "unit_pressure_label": "Давление",
        "unit_wind_speed_label": "Скорость ветра",
        "unit_temp_label_alt": "температуры",
        "unit_pressure_label_alt": "давления",
        "unit_wind_speed_label_alt": "скорости ветра",
        
        "weather_data_labels": {
            "description": "Погода",
            "temperature": "Температура",
            "humidity": "Влажность",
            "precipitation": "Вероятность осадков",
            "pressure": "Давление",
            "wind_speed": "Скорость ветра",
            "visibility": "Видимость",
            "feels_like": "Ощущается как",
            "clouds": "Облачность",
            "wind_direction": "Направление ветра",
            "wind_gust": "Порывы ветра"
        },

        "weather_param_labels": {
            "description": "Погода",
            "temperature": "Температура",
            "feels_like": "Ощущается как",
            "humidity": "Влажность",
            "precipitation": "Вероятность осадков",
            "pressure": "Давление",
            "wind_speed": "Скорость ветра",
            "wind_direction": "Направление ветра",
            "wind_gust": "Порывы ветра",
            "clouds": "Облачность",
            "visibility": "Видимость"
        },

        "unit_selection_names": {
            "temp": {"C": "°C (Цельсий)", "F": "°F (Фаренгейт)", "K": "K (Кельвин)", "ICE": "Мороженки (🍦)"},
            "pressure": {"mmHg": "мм рт. ст.", "mbar": "мбар", "hPa": "гПа", "inHg": "дюйм. рт. ст."},
            "wind_speed": {"m/s": "м/с", "km/h": "км/ч", "mph": "миль/ч"}
        },
        "btn_save": "↩ Сохранить",

        "notification_labels": {
            "weather_threshold_notifications": "Оповещения об изменении погоды",
            "forecast_notifications": "Ежедневный прогноз",
            "bot_notifications": "Новости бота"
        },
        
        "unit_translations": {
            "temp": {"C": "°C", "F": "°F", "K": "К", "ICE": "🍦"},
            "pressure": {"mmHg": "мм рт. ст.", "mbar": "мбар", "hPa": "гПа", "inHg": "дюйм. рт."},
            "wind_speed": {"m/s": "м/с", "km/h": "км/ч", "mph": "миль/ч"}
        },
        "months": {
            1: "января", 2: "февраля", 3: "марта", 4: "апреля", 5: "мая", 6: "июня",
            7: "июля", 8: "августа", 9: "сентября", 10: "октября", 11: "ноября", 12: "декабря"
        },
        "weekdays": {
            "Monday": "Понедельник", "Tuesday": "Вторник", "Wednesday": "Среда",
            "Thursday": "Четверг", "Friday": "Пятница", "Saturday": "Суббота", "Sunday": "Воскресенье"
        },
        "wind_directions": {
            (337.5, 360): "Север", (0, 22.5): "Север", (22.5, 67.5): "Северо-Восток",
            (67.5, 112.5): "Восток", (112.5, 157.5): "Юго-Восток", (157.5, 202.5): "Юг",
            (202.5, 247.5): "Юго-Запад", (247.5, 292.5): "Запад", (292.5, 337.5): "Северо-Запад"
        },
        "bad_weather_descriptions": [
            "Гроза с небольшим дождём", "Гроза с дождём", "Гроза с сильным дождём",
            "Слабая гроза", "Гроза", "Сильная гроза", "Неустойчивая гроза",
            "Гроза с лёгкой моросью", "Гроза с моросью", "Гроза с сильной моросью",
            "Лёгкая морось", "Морось", "Сильная морось", "Лёгкий моросящий дождь",
            "Моросящий дождь", "Сильный моросящий дождь", "Ливень и морось",
            "Сильный ливень и морось", "Моросящий ливень", "Небольшой дождь",
            "Умеренный дождь", "Сильный дождь", "Очень сильный дождь",
            "Чрезвычайно сильный дождь", "Ледяной дождь", "Лёгкий ливень",
            "Ливень", "Сильный ливень", "Неустойчивый ливень", "Небольшой снег",
            "Снег", "Сильный снег", "Мокрый снег", "Слабый ливень с мокрым снегом",
            "Ливень с мокрым снегом", "Небольшой дождь со снегом", "Дождь со снегом",
            "Слабый ливень со снегом", "Ливень со снегом", "Сильный ливень со снегом"
        ],
        "weather_emoji_map": {
            "гроза": "🌩", "морось": "🌫", "дождь": "☔️",
            "ливень": "🌧", "снег": "❄️", "туман": "🌁"
        },
        "severity_map": {
            "гроза": 5, "сильный ливень": 4, "сильный снег": 4,
            "ливень": 3, "дождь": 2, "морось": 1
        }
    },
    
    # ================= ENGLISH =================
    "en": {
        "unknown_command": "😔 I didn't understand that. Please use the menu commands.",
        "decorative_message_menu": "Choose an option:",
        "decorative_message_settings": "Choose a setting:",
        "basic_keyboard_button_1": "🌤 Current Weather",
        "basic_keyboard_button_2": "📅 Forecast",
        "basic_keyboard_button_3": "⚙️ Settings",
        "settings_keyboard_button_1": "🏙 Change City",
        "settings_keyboard_button_2": "🔔 Notifications",
        "settings_keyboard_button_3": "☀️ Weather Data",
        "settings_keyboard_button_4": "📏 Units",
        "settings_keyboard_button_5": "↩ Back",
        "settings_keyboard_button_language": "🌍 Language",
        "error_unknown_city": "⚠ First, please set your city in Settings.",
        "error_unknown_forecast": "⚠ Could not retrieve the forecast.",
        "error_issue_forecast": "⚠ An error occurred while processing the forecast.",
        "forecast_header": "<b>{day_name}, {date}</b>",
        "forecast_desc": "▸ Weather: {description}",
        "forecast_temp_range": "▸ Temp: {min}{unit} to {max}{unit}",
        "forecast_temp_single": "▸ Temp: {temp}{unit}",
        "forecast_feels": "▸ Feels like: {temp}{unit}",
        "forecast_humidity": "▸ Humidity: {val}%",
        "forecast_precip": "▸ Precipitation: {val}%",
        "forecast_pressure": "▸ Pressure: {val} {unit}",
        "forecast_wind": "▸ Wind: {val} {unit}",
        "forecast_wind_dir": "▸ Wind Dir: {dir} ({deg}°)",
        "forecast_gust": "▸ Wind Gust: {val} {unit}",
        "forecast_clouds": "▸ Clouds: {val}%",
        "forecast_visibility": "▸ Visibility: {val} m",
        "separator": "─" * 21,
        "greet_returning": "Welcome back, {name}!\nYour main city is {city}.",
        "greet_new": "Hi, {name}!\n\nTo start using the bot, please send your coordinates or type the city name manually.",
        "button_geo": "📍 Send Coordinates",
        "error_no_city": "⚠ Please set your city first.",
        "error_weather_fetch": "⚠ Could not retrieve weather data.",
        "weather_current_header": "Current weather in {city}:",
        "weather_footer": "⛄️ Dress warmly!",
        "changecity_current": "▸ Your current city is {city}. \n\nEnter the new city name to update.",
        "changecity_none": "You haven't set a city yet! \nEnter a city name.",
        "btn_cancel": "✖ Cancel",
        "notifications_menu_btn": "🔔 Notifications",
        "notifications_menu_text": "Select the notifications you want to receive:",
        "error_user_not_found": "Error: User not found.",
        "stop_success": "🔕 The bot will no longer send notifications.\nGo to Settings to enable them again.",
        "stop_error": "An error occurred while disabling notifications. Try again later.",
        "daily_forecast_title": "<blockquote>📅 Daily Weather Forecast</blockquote>",
        "daily_forecast_updated": "[Updated at {time}]",
        "settings_units_header": "Your current units are:",
        "settings_units_temp": "▸ Temperature: {val}",
        "settings_units_pressure": "▸ Pressure: {val}",
        "settings_units_wind": "▸ Wind Speed: {val}",
        "settings_units_choose": "Choose a parameter to change:",
        "error_user_not_found_start": "Error: User not found. Try /start.",
        "btn_back": "↩ Back",
        "settings_weather_data_btn": "☀️ Weather Data",
        "settings_weather_data_text": "Choose data to be displayed:",
        "menu_weather_now": "🌤 Current Weather",
        "menu_forecast": "📅 Forecast",
        "menu_settings": "⚙️ Settings",
        "menu_change_city": "🏙 Change City",
        "menu_notifications": "🔔 Notifications",
        "menu_back": "↩ Back",
        "menu_units": "📏 Units",
        "menu_weather_data": "☀️ Weather Data",
        "menu_language": "🌍 Language",
        "help_title": "Bot Commands:",
        "help_start": "▸ /start — Start the bot.",
        "help_stop": "▸ /stop — Disable bot.",
        "help_weather": "▸ /weather — Get current weather.",
        "help_changecity": "▸ /changecity — Change city.",
        "help_forecast": "▸ /weatherforecast — Get weather forecast.",
        "help_help": "▸ /help — Get list of commands.",
        "changecity_prompt_retry": "Enter the new city name to update!",
        "changecity_error_command": "‼️ Please send a city name, not a command!",
        "changecity_error_invalid": "‼️ City name can only contain letters, spaces, and hyphens!",
        "changecity_success_update": "Your main city is now {city}!",
        "changecity_success_same": "{city} is already your main city.",
        "greet_success_end": "☀️ Enjoy using the bot!",
        "error_invalid_city_command": "‼️ Please send a city name, not a command!",
        "error_invalid_city_chars": "‼️ City name can only contain letters, spaces, and hyphens!",
        "error_city_not_found_coords": "Could not determine city from coordinates. Please enter it manually.",
        "error_no_input": "Please enter a city or send coordinates.",
        "settings_unit_select_prompt": "Select unit for {param}:",
        "unknown_direction": "Unknown",
        "error_technical_glitch": "Oops... A small technical glitch occurred!\nPlease try again later ~o~",
        "weather_summary_clear": "🌤 No precipitation expected today.",
        "weather_summary_range": "{emoji} {desc} is expected from {start} to {end}.",
        "weather_summary_single": "{emoji} {desc} is expected at {time}.",
        "language_select_prompt": "Select interface language:",
        "language_set_success": "✅ Language changed to English.",
        "warning_no_forecast": "⚠ No forecast for {date} in {city}",
        "forecast_footer": "❄️ Cold always precedes spring.",
        "forecast_menu_title": "Select a time to receive the weather forecast:",

        # --- TIMER TEXTS ---
        "notification_header": "<blockquote>{emoji} Attention!</blockquote>\nWeather in {city} has changed!",
        "notification_footer": "\n🌟 Don't worry — the weather will get better.",
        "notification_trend_up": "⇑",
        "notification_trend_down": "⇓",
        "notification_trend_arrow": "▸",
        
        "help_header": "🤖 <b>Available Commands:</b>",
        "help_cmds": {
            "/start": "🏠 Main Menu",
            "/weather": "🌤 Current Weather",
            "/forecast": "📅 Forecast",
            "/settings": "⚙️ Settings",
            "/changecity": "🏙 Change City",
            "/help": "ℹ️ Help"
        },
        "help_footer": "💡 <i>Type a city name to get its weather.</i>",

        "btn_forecast_today": "🌤 Today",
        "btn_forecast_tomorrow": "🌧 Tomorrow",
        "btn_forecast_week": "📆 Week",
        "unit_temp_label": "Temperature",
        "unit_pressure_label": "Pressure",
        "unit_wind_speed_label": "Wind Speed",
        "unit_temp_label_alt": "temperature",
        "unit_pressure_label_alt": "preassure",
        "unit_wind_speed_label_alt": "wind speed",

        "weather_data_labels": {
            "description": "Weather",
            "temperature": "Temperature",
            "humidity": "Humidity",
            "precipitation": "Precipitation",
            "pressure": "Pressure",
            "wind_speed": "Wind Speed",
            "visibility": "Visibility",
            "feels_like": "Feels Like",
            "clouds": "Clouds",
            "wind_direction": "Wind Direction",
            "wind_gust": "Wind Gust"
        },
        "weather_param_labels": {
            "description": "Weather",
            "temperature": "Temperature",
            "feels_like": "Feels Like",
            "humidity": "Humidity",
            "precipitation": "Precipitation",
            "pressure": "Pressure",
            "wind_speed": "Wind Speed",
            "wind_direction": "Wind Direction",
            "wind_gust": "Wind Gust",
            "clouds": "Clouds",
            "visibility": "Visibility"
        },
        "unit_selection_names": {
            "temp": {"C": "°C (Celsius)", "F": "°F (Fahrenheit)", "K": "K (Kelvin)", "ICE": "Ice Cream (🍦)"},
            "pressure": {"mmHg": "mmHg", "mbar": "mbar", "hPa": "hPa", "inHg": "inHg"},
            "wind_speed": {"m/s": "m/s", "km/h": "km/h", "mph": "mph"}
        },
        "btn_save": "↩ Save",

        "notification_labels": {
            "weather_threshold_notifications": "Weather Change Alerts",
            "forecast_notifications": "Daily Forecast",
            "bot_notifications": "Bot News"
        },
        "unit_translations": {
            "temp": {"C": "°C", "F": "°F", "K": "K", "ICE": "🍦"},
            "pressure": {"mmHg": "mmHg", "mbar": "mbar", "hPa": "hPa", "inHg": "inHg"},
            "wind_speed": {"m/s": "m/s", "km/h": "km/h", "mph": "mph"}
        },
        "months": {
            1: "January", 2: "February", 3: "March", 4: "April", 5: "May", 6: "June",
            7: "July", 8: "August", 9: "September", 10: "October", 11: "November", 12: "December"
        },
        "weekdays": {
            "Monday": "Monday", "Tuesday": "Tuesday", "Wednesday": "Wednesday",
            "Thursday": "Thursday", "Friday": "Friday", "Saturday": "Saturday", "Sunday": "Sunday"
        },
        "wind_directions": {
            (337.5, 360): "North", (0, 22.5): "North", (22.5, 67.5): "North-East",
            (67.5, 112.5): "East", (112.5, 157.5): "South-East", (157.5, 202.5): "South",
            (202.5, 247.5): "South-West", (247.5, 292.5): "West", (292.5, 337.5): "North-West"
        },
        "bad_weather_descriptions": [], 
        "weather_emoji_map": {
            "thunderstorm": "🌩", "drizzle": "🌫", "rain": "☔️",
            "shower": "🌧", "snow": "❄️", "fog": "🌁", "mist": "🌁"
        },
        "severity_map": {
            "thunderstorm": 5, "heavy shower": 4, "heavy snow": 4,
            "shower": 3, "rain": 2, "drizzle": 1
        }
    },
    
    # ================= KAZAKH =================
    "kk": {
        "unknown_command": "😔 Мен сізді түсінбедім. Мәзір командаларын қолданыңыз.",
        "decorative_message_menu": "Опцияны таңдаңыз:",
        "decorative_message_settings": "Баптауды таңдаңыз:",
        "basic_keyboard_button_1": "🌤 Ауа райын білу",
        "basic_keyboard_button_2": "📅 Болжам",
        "basic_keyboard_button_3": "⚙️ Баптаулар",
        "settings_keyboard_button_1": "🏙 Қаланы өзгерту",
        "settings_keyboard_button_2": "🔔 Хабарламалар",
        "settings_keyboard_button_3": "☀️ Ауа райы деректері",
        "settings_keyboard_button_4": "📏 Өлшем бірліктері",
        "settings_keyboard_button_5": "↩ Арқаға",
        "settings_keyboard_button_language": "🌍 Тіл",
        "error_unknown_city": "⚠ Алдымен баптауларда қалаңызды көрсетіңіз.",
        "error_unknown_forecast": "⚠ Ауа райы болжамын алу мүмкін болмады.",
        "error_issue_forecast": "⚠ Болжамды өңдеу кезінде қате шықты.",
        "forecast_header": "<b>{day_name}, {date}</b>",
        "forecast_desc": "▸ Ауа райы: {description}",
        "forecast_temp_range": "▸ Температура: {min}{unit}-тан {max}{unit}-қа дейін",
        "forecast_temp_single": "▸ Температура: {temp}{unit}",
        "forecast_feels": "▸ Сезіледі: {temp}{unit}",
        "forecast_humidity": "▸ Ылғалдылық: {val}%",
        "forecast_precip": "▸ Жауын-шашын ықтималдығы: {val}%",
        "forecast_pressure": "▸ Қысым: {val} {unit}",
        "forecast_wind": "▸ Жел: {val} {unit}",
        "forecast_wind_dir": "▸ Жел бағыты: {dir} ({deg}°)",
        "forecast_gust": "▸ Жел екпіні: {val} {unit}",
        "forecast_clouds": "▸ Бұлттылық: {val}%",
        "forecast_visibility": "▸ Көріну: {val} м",
        "separator": "─" * 21,
        "greet_returning": "Қайта оралуыңызбен, {name}!\nСіздің негізгі қалаңыз — {city}.",
        "greet_new": "Сәлем, {name}!\n\nБотты пайдалануды бастау үшін координаттарыңызды жіберіңіз немесе қала атын жазыңыз.",
        "button_geo": "📍 Координаттарды жіберу",
        "error_no_city": "⚠ Алдымен қалаңызды көрсетіңіз.",
        "error_weather_fetch": "⚠ Ауа райы деректерін алу мүмкін болмады.",
        "weather_current_header": "{city} қаласындағы ауа райы:",
        "weather_footer": "⛄️ Жылы киініңіз!",
        "changecity_current": "▸ Сіздің қазіргі қалаңыз — {city}. \n\nЖаңарту үшін жаңа қала атын енгізіңіз.",
        "changecity_none": "Сіз әлі қалаңызды көрсетпедіңіз! \nЖаңа қаланы көрсетіңіз.",
        "btn_cancel": "✖ Болдырмау",
        "notifications_menu_btn": "🔔 Хабарламалар",
        "notifications_menu_text": "Алғыңыз келетін хабарламаларды таңдаңыз:",
        "error_user_not_found": "Қате: пайдаланушы табылмады.",
        "stop_success": "🔕 Бот енді хабарлама жібермейді.\nҚосу үшін баптауларға кіріңіз.",
        "stop_error": "Хабарламаларды өшіру кезінде қате шықты. Кейінірек қайталап көріңіз.",
        "daily_forecast_title": "<blockquote>📅 Күнделікті ауа райы болжамы</blockquote>",
        "daily_forecast_updated": "[Жаңартылды: {time}]",
        "settings_units_header": "Қазіргі өлшем бірліктеріңіз:",
        "settings_units_temp": "▸ Температура: {val}",
        "settings_units_pressure": "▸ Қысым: {val}",
        "settings_units_wind": "▸ Жел жылдамдығы: {val}",
        "settings_units_choose": "Өзгертетін параметрді таңдаңыз:",
        "error_user_not_found_start": "Қате: пайдаланушы табылмады. /start басып көріңіз.",
        "btn_back": "↩ Арқаға",
        "settings_weather_data_btn": "☀️ Ауа райы деректері",
        "settings_weather_data_text": "Бот көрсететін деректерді таңдаңыз:",
        "menu_weather_now": "🌤 Ауа райын білу",
        "menu_forecast": "📅 Болжам",
        "menu_settings": "⚙️ Баптаулар",
        "menu_change_city": "🏙 Қаланы өзгерту",
        "menu_notifications": "🔔 Хабарламалар",
        "menu_back": "↩ Арқаға",
        "menu_units": "📏 Өлшем бірліктері",
        "menu_weather_data": "☀️ Ауа райы деректері",
        "menu_language": "🌍 Тіл",
        "help_title": "Бот командалары:",
        "help_start": "▸ /start — Ботты іске қосу.",
        "help_stop": "▸ /stop — Ботты өшіру.",
        "help_weather": "▸ /weather — Қазіргі ауа райын білу.",
        "help_changecity": "▸ /changecity — Қаланы өзгерту.",
        "help_forecast": "▸ /weatherforecast — Болжам алу.",
        "help_help": "▸ /help — Командалар тізімі.",
        "changecity_prompt_retry": "Жаңарту үшін жаңа қала атын енгізіңіз!",
        "changecity_error_command": "‼️ Команда емес, қала атын жіберіңіз!",
        "changecity_error_invalid": "‼️ Қала аты тек әріптерден, бос орындардан және дефистен тұруы керек!",
        "changecity_success_update": "Енді сіздің негізгі қалаңыз — {city}!",
        "changecity_success_same": "{city} — сіздің негізгі қалаңыз болып қалды.",
        "greet_success_end": "☀️ Ботты қолдану сізге ұнайды деп үміттенеміз!",
        "error_invalid_city_command": "‼️ Команда емес, қала атын жіберіңіз!",
        "error_invalid_city_chars": "‼️ Қала аты тек әріптерден, бос орындардан және дефистен тұруы керек!",
        "error_city_not_found_coords": "Координаттар бойынша қаланы анықтау мүмкін болмады. Қолмен енгізіңіз.",
        "error_no_input": "Қала атын енгізіңіз немесе координаттарды жіберіңіз.",
        "settings_unit_select_prompt": "{param} үшін өлшем бірлігін таңдаңыз:",
        "unknown_direction": "Беймәлім",
        "error_technical_glitch": "Қап... Техникалық ақау орын алды!\nСұранысты сәл кейінірек қайталаңыз ~o~",
        "weather_summary_clear": "🌤 Бүгін жауын-шашын күтілмейді.",
        "weather_summary_range": "{start}-дан {end}-қа дейін {emoji} {desc} күтіледі.",
        "weather_summary_single": "Сағат {time}-да {emoji} {desc} күтіледі.",
        "language_select_prompt": "Интерфейс тілін таңдаңыз:",
        "language_set_success": "✅ Тіл Қазақшаға өзгертілді.",
        "warning_no_forecast": "⚠ {date} күніне {city} қаласы үшін болжам жоқ",
        "forecast_footer": "❄️ Суық әрқашан көктемнің алдында болады.",
        "forecast_menu_title": "Ауа райы болжамын алу үшін уақытты таңдаңыз:",

        # --- TIMER TEXTS ---
        "notification_header": "<blockquote>{emoji} Назар аударыңыз!</blockquote>\n{city} қаласында ауа райы өзгерді!",
        "notification_footer": "\n🌟 Еңсеңізді түсірмеңіз — ауа райы әлі-ақ түзеледі.",
        "notification_trend_up": "⇑",
        "notification_trend_down": "⇓",
        "notification_trend_arrow": "▸",

        "help_header": "🤖 <b>Қолжетімді командалар:</b>",
        "help_cmds": {
            "/start": "🏠 Басты мәзір",
            "/weather": "🌤 Қазіргі ауа райы",
            "/forecast": "📅 Болжам",
            "/settings": "⚙️ Баптаулар",
            "/changecity": "🏙 Қаланы өзгерту",
            "/help": "ℹ️ Анықтама"
        },
        "help_footer": "💡 <i>Ауа райын білу үшін қала атын жазыңыз.</i>",

        "btn_forecast_today": "🌤 Бүгін",
        "btn_forecast_tomorrow": "🌧 Ертең",
        "btn_forecast_week": "📆 Апта",
        "unit_temp_label": "Температура",
        "unit_pressure_label": "Қысым",
        "unit_wind_speed_label": "Жел жылдамдығы",
        "unit_temp_label_alt": "температура",
        "unit_pressure_label_alt": "қысым",
        "unit_wind_speed_label_alt": "жел жылдамдығы",

        "weather_data_labels": {
            "description": "Сипаттама",
            "temperature": "Температура",
            "humidity": "Ылғалдылық",
            "precipitation": "Жауын-шашын",
            "pressure": "Қысым",
            "wind_speed": "Жел жылдамдығы",
            "visibility": "Көріну",
            "feels_like": "Сезіледі",
            "clouds": "Бұлттылық",
            "wind_direction": "Жел бағыты",
            "wind_gust": "Жел екпіні"
        },
        "weather_param_labels": {
            "description": "Сипаттама",
            "temperature": "Температура",
            "feels_like": "Сезіледі",
            "humidity": "Ылғалдылық",
            "precipitation": "Жауын-шашын",
            "pressure": "Қысым",
            "wind_speed": "Жел жылдамдығы",
            "wind_direction": "Жел бағыты",
            "wind_gust": "Жел екпіні",
            "clouds": "Бұлттылық",
            "visibility": "Көріну"
        },
        "unit_selection_names": {
            "temp": {"C": "°C (Цельсий)", "F": "°F (Фаренгейт)", "K": "K (Кельвин)", "ICE": "Балмұздақ (🍦)"},
            "pressure": {"mmHg": "мм с.б.", "mbar": "мбар", "hPa": "гПа", "inHg": "дюйм с.б."},
            "wind_speed": {"m/s": "м/с", "km/h": "км/сағ", "mph": "миль/сағ"}
        },
        "btn_save": "↩ Сақтау",
        "notification_labels": {
            "weather_threshold_notifications": "Ауа райының өзгеруі",
            "forecast_notifications": "Күнделікті болжам",
            "bot_notifications": "Бот жаңалықтары"
        },
        "unit_translations": {
            "temp": {"C": "°C", "F": "°F", "K": "К", "ICE": "🍦"},
            "pressure": {"mmHg": "мм с.б.", "mbar": "мбар", "hPa": "гПа", "inHg": "дюйм с.б."},
            "wind_speed": {"m/s": "м/с", "km/h": "км/сағ", "mph": "миль/сағ"}
        },
        "months": {
            1: "қаңтар", 2: "ақпан", 3: "наурыз", 4: "сәуір", 5: "мамыр", 6: "маусым",
            7: "шілде", 8: "тамыз", 9: "қыркүйек", 10: "қазан", 11: "қараша", 12: "желтоқсан"
        },
        "weekdays": {
            "Monday": "Дүйсенбі", "Tuesday": "Сейсенбі", "Wednesday": "Сәрсенбі",
            "Thursday": "Бейсенбі", "Friday": "Жұма", "Saturday": "Сенбі", "Sunday": "Жексенбі"
        },
        "wind_directions": {
            (337.5, 360): "Солтүстік", (0, 22.5): "Солтүстік", (22.5, 67.5): "Солтүстік-Шығыс",
            (67.5, 112.5): "Шығыс", (112.5, 157.5): "Оңтүстік-Шығыс", (157.5, 202.5): "Оңтүстік",
            (202.5, 247.5): "Оңтүстік-Батыс", (247.5, 292.5): "Батыс", (292.5, 337.5): "Солтүстік-Батыс"
        },
        "bad_weather_descriptions": [
            # Русские описания используются для логики проверки, переводить их тут не обязательно, 
            # так как проверка идет по ответу API, который по умолчанию RU для логики бота
            "Гроза с небольшим дождём", "Гроза с дождём", "Гроза с сильным дождём",
            "Слабая гроза", "Гроза", "Сильная гроза", "Неустойчивая гроза",
            "Гроза с лёгкой моросью", "Гроза с моросью", "Гроза с сильной моросью",
            "Лёгкая морось", "Морось", "Сильная морось", "Лёгкий моросящий дождь",
            "Моросящий дождь", "Сильный моросящий дождь", "Ливень и морось",
            "Сильный ливень и морось", "Моросящий ливень", "Небольшой дождь",
            "Умеренный дождь", "Сильный дождь", "Очень сильный дождь",
            "Чрезвычайно сильный дождь", "Ледяной дождь", "Лёгкий ливень",
            "Ливень", "Сильный ливень", "Неустойчивый ливень", "Небольшой снег",
            "Снег", "Сильный снег", "Мокрый снег", "Слабый ливень с мокрым снегом",
            "Ливень с мокрым снегом", "Небольшой дождь со снегом", "Дождь со снегом",
            "Слабый ливень со снегом", "Ливень со снегом", "Сильный ливень со снегом"
        ],
        "weather_emoji_map": {
            "гроза": "🌩", "морось": "🌫", "дождь": "☔️",
            "ливень": "🌧", "снег": "❄️", "туман": "🌁"
        },
        "severity_map": {
            "гроза": 5, "сильный ливень": 4, "сильный снег": 4,
            "ливень": 3, "дождь": 2, "морось": 1
        }
    }
}