"""Added weather tracking fields to checked_cities

Revision ID: a726d1e0f176
Revises: 4bf0a014a061
Create Date: 2025-02-07 19:36:20.916797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a726d1e0f176'
down_revision: Union[str, None] = '4bf0a014a061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checked_cities', sa.Column('last_temperature', sa.Float(), nullable=True))
    op.add_column('checked_cities', sa.Column('last_wind_speed', sa.Float(), nullable=True))
    op.add_column('checked_cities', sa.Column('last_humidity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checked_cities', 'last_humidity')
    op.drop_column('checked_cities', 'last_wind_speed')
    op.drop_column('checked_cities', 'last_temperature')
    # ### end Alembic commands ###
